substitutions:
  name: "TheAirFlowProject"

esphome:
  name: the_airflow_project
  friendly_name: The AirFlow Project

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "TheAirFlowProject"
    password: "TheAirFlowSetup"

captive_portal:
ota:
  
web_server:
  port: 80
  local: true

api:
logger:

# ==========================================
# HARDWARE CONFIGURATION
# Uncomment the modules you want to enable by removing the #:
# ==========================================
packages:
  #Base system (Always required!)
  base_system:
    url: https://github.com/Muchajoe/The-AirFlow-Project
    file: Firmware/ESPHome/extensions/base.yaml
    refresh: 0s

  #Physical Rotary Encoder (Pins: CLK -> 5 | DT -> 4 | SW (Button) -> 3)
  #rotary:
    #url: https://github.com/Muchajoe/The-AirFlow-Project
    #file: Firmware/ESPHome/extensions/rotary.yaml
    #refresh: 0s
    
  #Power Measurement Requires J1 to be solder-bridged. This reserves H3 Pin 7
  #measurement:
    #url: https://github.com/Muchajoe/The-AirFlow-Project
    #file: Firmware/ESPHome/extensions/measurement.yaml
    #refresh: 0s
