substitutions:
  name: "TheAirFlowProject"

esphome:
  name: the_airflow_project
  friendly_name: The AirFlow Project

esp32:
  board: esp32-s3-devkitc-1 # Kompatibles Profil für den ESP32-S3 Zero
  framework:
    type: arduino

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap_timeout: 10s
  
  ap:
    ssid: "TheAirFlowProject"
    password: "123456789"

captive_portal:
  
web_server:
  port: 80
  local: true

api:
ota:
logger:

# ==========================================
# HARDWARE KONFIGURATION
# Entferne das '#' vor den Modulen, die du aktivieren möchtest:
# ==========================================
packages:
  # 1. Das Grundsystem (Immer erforderlich!)
  base_system: github://Muchajoe/The-AirFlow-Project/Firmware/ESPHome/extensions/base.yaml
  #refresh: 1s
  # 2. Strommessung & Hardware-Schutz
  # measurement_addon:
  #   url: github://DEIN_GITHUB_NAME/DEIN_REPO_NAME/esphome/measurement.yaml
  #   refresh: 1d

  # 3. Physischer Drehregler
  # rotary_addon:
  #   url: github://DEIN_GITHUB_NAME/DEIN_REPO_NAME/esphome/rotary.yaml
  rotary_encoder: github://Muchajoe/The-AirFlow-Project/Firmware/ESPHome/extensions/measurement.yaml
  #   refresh: 1d