substitutions:
  name: "TheAirFlowProject"

esphome:
  name: the_airflow_project
  friendly_name: The AirFlow Project

esp32:
  board: esp32-s3-devkitc-1 # Kompatibles Profil für den ESP32-S3 Zero
  framework:
    type: arduino

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "TheAirFlowProject"
    password: "123456789"

captive_portal:
  
web_server:
  port: 80
  local: true

api:
ota:
logger:

# ==========================================
# HARDWARE KONFIGURATION
# Entferne das '#' vor den Modulen, die du aktivieren möchtest:
# ==========================================
packages:
  # 1. Das Grundsystem (Immer erforderlich!)
  base_system:
    url: https://github.com/Muchajoe/The-AirFlow-Project
    file: Firmware/ESPHome/extensions/base.yaml
    refresh: 0s

  rotary:
    url: https://github.com/Muchajoe/The-AirFlow-Project
    file: Firmware/ESPHome/extensions/rotary.yaml.yaml
    refresh: 0s
    
  measurement:
    url: https://github.com/Muchajoe/The-AirFlow-Project
    file: Firmware/ESPHome/extensions/measurement.yaml
    refresh: 0s
