sensor:
  # ==========================================
  # 
  # ==========================================
  - platform: adc
    pin: 7
    id: efuse_voltage
    name: "eFuse Raw Voltage"
    attenuation: 11db
    update_interval: 100ms  
    filters:
      - sliding_window_moving_average:
          window_size: 20   
          send_every: 10    
    accuracy_decimals: 3

  # ==========================================
  # 
  # ==========================================
  - platform: template
    name: "Fan Power Consumption"
    id: system_power
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    update_interval: 1s
    lambda: |-
      float v_cs = id(efuse_voltage).state;
      
      if (isnan(v_cs)) {
        return 0.0;
      }

      const float R_CS = 330.0;        
      const float K_CS = 500.0;          
      const float SYSTEM_VOLTAGE = 12.0;
      const float I_LIMIT = 2.466;   
      const float BOARD_CALIBRATION = 1.087;
      
      // ==========================================
      // 
      // ==========================================
      const float VOLTAGE_OFFSET = 0.150; 
      

      v_cs = v_cs - VOLTAGE_OFFSET;
      
      if (v_cs < 0.0) {
        v_cs = 0.0;
      }
      
      float current_A = ((v_cs / R_CS) * K_CS) * BOARD_CALIBRATION;
      
      if (current_A < 0.05) {
        current_A = 0.0;
      }
      
      float power_W = current_A * SYSTEM_VOLTAGE;

      return power_W;